/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ArchiveSlugRouteImport } from './routes/archive.$slug'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminEditionBuilderRouteImport } from './routes/admin.edition-builder'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAgentRunsRouteImport } from './routes/admin.agent-runs'

const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugRoute = ArchiveSlugRouteImport.update({
  id: '/archive/$slug',
  path: '/archive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/admin/sponsors',
  path: '/admin/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditionBuilderRoute = AdminEditionBuilderRouteImport.update({
  id: '/admin/edition-builder',
  path: '/admin/edition-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentRunsRoute = AdminAgentRunsRouteImport.update({
  id: '/admin/agent-runs',
  path: '/admin/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/edition-builder': typeof AdminEditionBuilderRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/edition-builder': typeof AdminEditionBuilderRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/admin': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/edition-builder': typeof AdminEditionBuilderRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise'
    | '/admin/agent-runs'
    | '/admin/content'
    | '/admin/edition-builder'
    | '/admin/sources'
    | '/admin/sponsors'
    | '/archive/$slug'
    | '/admin/'
    | '/archive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/admin/agent-runs'
    | '/admin/content'
    | '/admin/edition-builder'
    | '/admin/sources'
    | '/admin/sponsors'
    | '/archive/$slug'
    | '/admin'
    | '/archive'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise'
    | '/admin/agent-runs'
    | '/admin/content'
    | '/admin/edition-builder'
    | '/admin/sources'
    | '/admin/sponsors'
    | '/archive/$slug'
    | '/admin/'
    | '/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AdminAgentRunsRoute: typeof AdminAgentRunsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEditionBuilderRoute: typeof AdminEditionBuilderRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  ArchiveSlugRoute: typeof ArchiveSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$slug': {
      id: '/archive/$slug'
      path: '/archive/$slug'
      fullPath: '/archive/$slug'
      preLoaderRoute: typeof ArchiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edition-builder': {
      id: '/admin/edition-builder'
      path: '/admin/edition-builder'
      fullPath: '/admin/edition-builder'
      preLoaderRoute: typeof AdminEditionBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agent-runs': {
      id: '/admin/agent-runs'
      path: '/admin/agent-runs'
      fullPath: '/admin/agent-runs'
      preLoaderRoute: typeof AdminAgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  AdminAgentRunsRoute: AdminAgentRunsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEditionBuilderRoute: AdminEditionBuilderRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  ArchiveSlugRoute: ArchiveSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
