/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsSubmitRouteImport } from './routes/events.submit'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ArchiveSlugRouteImport } from './routes/archive.$slug'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEditionBuilderRouteImport } from './routes/admin.edition-builder'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAgentRunsRouteImport } from './routes/admin.agent-runs'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSubmitRoute = EventsSubmitRouteImport.update({
  id: '/events/submit',
  path: '/events/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugRoute = ArchiveSlugRouteImport.update({
  id: '/archive/$slug',
  path: '/archive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/admin/sponsors',
  path: '/admin/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditionBuilderRoute = AdminEditionBuilderRouteImport.update({
  id: '/admin/edition-builder',
  path: '/admin/edition-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentRunsRoute = AdminAgentRunsRouteImport.update({
  id: '/admin/agent-runs',
  path: '/admin/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/edition-builder': typeof AdminEditionBuilderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/edition-builder': typeof AdminEditionBuilderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/admin': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/edition-builder': typeof AdminEditionBuilderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertise'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/agent-runs'
    | '/admin/articles'
    | '/admin/content'
    | '/admin/edition-builder'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/sources'
    | '/admin/sponsors'
    | '/archive/$slug'
    | '/articles/$slug'
    | '/events/$slug'
    | '/events/submit'
    | '/admin/'
    | '/archive/'
    | '/articles/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/agent-runs'
    | '/admin/articles'
    | '/admin/content'
    | '/admin/edition-builder'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/sources'
    | '/admin/sponsors'
    | '/archive/$slug'
    | '/articles/$slug'
    | '/events/$slug'
    | '/events/submit'
    | '/admin'
    | '/archive'
    | '/articles'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/agent-runs'
    | '/admin/articles'
    | '/admin/content'
    | '/admin/edition-builder'
    | '/admin/login'
    | '/admin/pipeline'
    | '/admin/sources'
    | '/admin/sponsors'
    | '/archive/$slug'
    | '/articles/$slug'
    | '/events/$slug'
    | '/events/submit'
    | '/admin/'
    | '/archive/'
    | '/articles/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAgentRunsRoute: typeof AdminAgentRunsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEditionBuilderRoute: typeof AdminEditionBuilderRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  ArchiveSlugRoute: typeof ArchiveSlugRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsSubmitRoute: typeof EventsSubmitRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/submit': {
      id: '/events/submit'
      path: '/events/submit'
      fullPath: '/events/submit'
      preLoaderRoute: typeof EventsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$slug': {
      id: '/archive/$slug'
      path: '/archive/$slug'
      fullPath: '/archive/$slug'
      preLoaderRoute: typeof ArchiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edition-builder': {
      id: '/admin/edition-builder'
      path: '/admin/edition-builder'
      fullPath: '/admin/edition-builder'
      preLoaderRoute: typeof AdminEditionBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agent-runs': {
      id: '/admin/agent-runs'
      path: '/admin/agent-runs'
      fullPath: '/admin/agent-runs'
      preLoaderRoute: typeof AdminAgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAgentRunsRoute: AdminAgentRunsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEditionBuilderRoute: AdminEditionBuilderRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  ArchiveSlugRoute: ArchiveSlugRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsSubmitRoute: EventsSubmitRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
