/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveSlugRouteImport } from './routes/archive.$slug'

const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveSlugRoute = ArchiveSlugRouteImport.update({
  id: '/archive/$slug',
  path: '/archive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/archive': typeof ArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/archive/$slug': typeof ArchiveSlugRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/advertise' | '/archive/$slug' | '/archive/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/advertise' | '/archive/$slug' | '/archive'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertise'
    | '/archive/$slug'
    | '/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  ArchiveSlugRoute: typeof ArchiveSlugRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$slug': {
      id: '/archive/$slug'
      path: '/archive/$slug'
      fullPath: '/archive/$slug'
      preLoaderRoute: typeof ArchiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  ArchiveSlugRoute: ArchiveSlugRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
